### ISSUE TITLE
permission deneid.

### ISSUE THREAD

**Issue by zeeshanmustafa** [CISC3120SP18/SamplePrograms#1]
@graychan @huichen-cs @CISC3120SP18/team-numero-dos 

here is the error I am getting every time I am trying to push BeerSong .It says permission denied to zeeshanmustafa. 
 1 file changed, 2 insertions(+), 1 deletion(-)
Naumans-Air:01_31 Zeeshan$ git push
remote: Permission to CISC3120SP18/SamplePrograms.git denied to zeeshanmustafa.
fatal: unable to access 'https://github.com/CISC3120SP18/SamplePrograms.git/': The requested URL returned error: 403

**Comment by huichen-cs** [comment]
@zeeshanmustafa , @CISC3120SP18/team-numero-dos, 

This is expected. In a Web browser, you can browse the repository. However, the repository is to share sample programs to the class, i.e., everyone in the class. No write permission is given to the students; otherwise, the sample programs becomes a mess. 

As I said in the assignment description, you will  have to ***copy the sample program to your own weekly practice repository, and work from there***.

**Comment by zeeshanmustafa** [comment]
@huichen-cs  I just uploaded my work where i have to fix the bugs. Class starts at 2:15 but I just checked my grades and I recived U. just wondering.
